<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_DEBUG' => '1',
  'APP_SECRET' => '2f703a84cf5d5e1e91a163d714c4f395',
  'DATABASE_URL' => 'mysql://root:root@localhost:8889/pe5?serverVersion=8.0.35',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$',
);
